### PR TITLE
Added ability for upstream proxy

### PR DESCRIPTION
**Pull request by jeddytier4**
Can use upstream proxies for http and connect, including proxies with authentication.  New to golang, so any comments are appreciated.  Added a configuration line to allow removal of the Via header, referenced in issue #8 .

### CODE REVIEW

**Comment by mholt** [comment]
Hey, thank you for your contribution! Obviously a lot of work went into this, especially since you're new to the language.

I think, first, we would like to discuss a few points. What is the use case for this feature? Also, what is the value of removing the Via header, when that alone does not conceal the use of a proxy?

**Comment by sergeyfrolov** [comment]
I also would like to thank you for your contribution, PRs are most welcome!  
+1 to everything @mholt said. We try to keep this code as concise as possible for ease of development and security sake.  

#### Another way to do this
In my opinion, an ideal solution to this use-case would be `forwardproxy` and `proxy` directives chained together. This might require some changes to `proxy`, `forwardproxy` plugins or Caddy itself, but integrating this with good and reliable work done by folks who maintain proxy plugin, instead of reimplementing proxy inside of forwardproxy, seems like the best approach to me.  
Here's an extremely simple way to do this, which might work, and only involves changing `forwardproxy`. Currently, `forwardproxy` goes before `proxy` in middleware chain, so `proxy` won't see any requests if those two plugins are enabled together. However, we can add a directive to `forwardproxy` that's going to do forwardproxy things with regard to talking to client, and push requests(that are modified by forwardproxy) further in middleware chain, instead of sending modified request to remote server on its own. At this point, `proxy` should be able to get the request and unleash the power of the plugin.

**Comment by jeddytier4** [comment]
@mholt Thank you, sorry for the list, but I think in outlines :)

1. Use case:  I'm currently testing this as way to load balance requests in a multi-wan environment, but I have used upstream proxies(normally using squid) in the past to get more granular detail on traffic coming from zones not directly connected to the internet (internal testing site).

2. Via Header:  The Via header is used by most proxy detecting software as the first check, without it they have to resort to RTC tricks or other methods of fingerprinting, basically this is eliminating the low hanging fruit for detection.

@sergeyfrolov I'm wrapping my head around what you've said.  I'm certain that there was an easier way to do what I did :).

**Comment by sergeyfrolov** [comment]
In this case, I am not sure if you need to use `forwardproxy`, or make any changes to Caddy.  
Caddy's `proxy` [plugin](https://caddyserver.com/docs/proxy) is good at load-balancing, and then your squids will handle CONNECT requests.

**Comment by la0wei** [comment]
hello,any configration update about using upstream proxy?

**Comment by sergeyfrolov** [comment]
@la0wei if I understand the use-case correctly, `forwardproxy` is not the right tool for the first hop, use `proxy` plugin instead.

**Comment by sergeyfrolov** [comment]
I assume I can close this PR now, feel free to open an issue if you have further problems.
Please use `proxy` plugin if you need load balancer or reverse proxy, that's what it is for.

**Pull request closed without merging**
