### PR TITLE
Caddy2 fix tests

### PR DESCRIPTION
**Pull request by johnzhanghua**
### 1. What does this change do, exactly?
This change based on the [PR 74](https://github.com/caddyserver/forwardproxy/pull/74) , to fix the broken test cases

### 2. Please link to the relevant issues.
[PR 74](https://github.com/caddyserver/forwardproxy/pull/74)  tests failed

### 4. Checklist

- [ x] I have written tests and verified that they fail without my change
- [ x] I made pull request as minimal and simple as possible. If change is not small or additional dependencies are required, I opened an issue to propose and discuss the design first
- [x ] I have squashed any insignificant commits
- [ x] This change has comments for package types, values, functions, and non-obvious lines of code

### CODE REVIEW

**Comment by gaby** [comment]
@johnzhanghua Thanks for the PR, some of the changes introduced this issue:

```
[/home/runner/work/forwardproxy/forwardproxy/forwardproxy.go:397] - G104 (CWE-703): Errors unhandled. (Confidence: HIGH, Severity: LOW)
    396: 	}
  > 397: 	r.Body.Close()
    398: 
```

**Comment by gaby** [comment]
@johnzhanghua GoSec issues are gone, some of the tests still fail

**Comment by gaby** [comment]
@johnzhanghua You can run them locally using `go test -v ./...`

**Comment by johnzhanghua** [comment]
> @johnzhanghua You can run them locally using `go test -v ./...` with go 1.21

Added a wait, should be fine now. Tested locally with Docker ubuntu.   Could you please trigger the checks ?

**Comment by gaby** [comment]
@johnzhanghua Awesome, will start reviewing

**Comment by gaby** [comment]
@johnzhanghua Thank you for the PR, I will keep working on the `caddy2` branch

**Pull request merged**
