### PR TITLE
Hashed passwords in basic_auth

### PR DESCRIPTION
**Pull request by proofrock**
Hi all

### 1. What does this change do, exactly?

This PR introduces a mechanism to specify passwords as hashed strings, in `basic_auth`. The proposed implementation allows for hex-encoded, SHA-256 hashes; more algorithms can be plugged in easily and I'll be glad to do it if this PR is of interest. The current authentication schema is of course maintained, and the current configuration files are still accepted as they are.

The `basic_auth` node now has three values, with the third being the algorithm. `RAW` is plain text (current), and can be omitted. `SHA256` was added. An example of a valid caddyfile:

```caddyfile
:80
route {
  forward_proxy {
    basic_auth test1 pass1
    basic_auth test2 pass2 RAW
    # Password is "pass3" hashed
    basic_auth test3 3acb59306ef6e660cf832d1d34c4fba3d88d616f0bb5c2a9e0f82d18ef6fc167 SHA256
  }
}
```

There are no added libraries or dependencies. I tried to minimize the amount of code changes; this is my first contribution, and I may have departed from standards somewhere; please let me know (in particular if I should write more comments).

The proposed code hashes the provided password at every request. It would be quite easy to cache the password after the first valid authentication, to speed up subsequent requests. Let me know if this is of interest.

To test the changes "live", apply the patches, then put the config above in a file `caddyfile` and run

```bash
xcaddy run -- --config caddyfile
```

Then

```bash
curl -x http://test1:pass1@localhost:80 https://ifconfig.io
curl -x http://test2:pass2@localhost:80 https://ifconfig.io
curl -x http://test3:pass3@localhost:80 https://ifconfig.io
curl -x http://test3:abcde@localhost:80 https://ifconfig.io # This one fails
```

### 2. Please link to the relevant issues.

None I am aware of.

### 3. Which documentation changes (if any) need to be made because of this PR?

I have modified `README.md` in the sections about `basic_auth`.

### 4. Checklist

- [x] I have written tests and verified that they fail without my change
- [x] I made pull request as minimal and simple as possible. If change is not small or additional dependencies are required, I opened an issue to propose and discuss the design first
- [x] I have squashed any insignificant commits
- [x] This change has comments for package types, values, functions, and non-obvious lines of code

### CODE REVIEW

**Comment by proofrock** [comment]
As required by the `CONTRIBUTING.md` file, I submitted the CLA, but I couldn't change the address from the `@gmail.com` one. I am afraid that it's different from my main address on github's , even if it's among the registered ones.

**Comment by proofrock** [comment]
I have also implemented hashing. I see it already in the second commit of this PR.

**Comment by mholt** [comment]
SHA256 is not a good hash for passwords IMO, since it is too fast. A proper KDF would make for a better hash. Bcrypt, for example, like Caddy's standard HTTP `basic_auth` middleware uses. This helps prevent brute-forcing.

The caching of the result also need to be done thoughtfully.

Do you think we could just reuse the code that is already in Caddy's basicauth module?

**Comment by proofrock** [comment]
Hi, thanks for your time!

Argon2 or Bcrypt can be plugged in without any trouble. I have to check Go support for SHA3 but it should be straightforward. 

I wrote this to avoid having to specify the password in plaintext, in the current interim while there isn't proper implementation using caddy's methods. As such, I (IMHO, most of all H since I am no one to speak 😅) see it as an improvement on the current situation. 

I don't admittedly know caddy's basicauth module code, so I cannot comment on that - yet. 

Thanks again!

**Comment by mholt** [comment]
SHA3 is also fast (esp. in hardware) -- I would avoid SHA for passwords entirely.

In its current state, I don't think this approach is acceptable, so I will respectfully close this PR, but take a look at Caddy's basic auth middleware and see if you can utilize it (wrap it, integrate it somehow, I'm not entirely sure off the top of my head) to avoid re-implementing tricky code.

**Pull request closed without merging**
